services:
  app:
    image: ghcr.io/sasivarnasarma/taskflow:${TAG:-latest}
    container_name: taskflow-prod
    env_file:
      - path: .env
        required: false
    ports:
      - "${HOST_IP:-0.0.0.0}:${HOST_PORT:-5279}:5279"
    restart: unless-stopped
